services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache-auth
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db-auth
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
    restart: always

  db-auth:
    image: mysql:latest
    container_name: mysql-db-auth
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb-auth
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-auth
    depends_on:
      - db-auth
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db-auth
      MYSQL_ROOT_PASSWORD: root
    restart: always

volumes:
  db_data:
